/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportRouteImport } from './routes/report'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NearbyRouteImport } from './routes/nearby'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AddAtmRouteImport } from './routes/add-atm'
import { Route as AdminXYGRouteImport } from './routes/AdminXYG'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminXYGIndexRouteImport } from './routes/AdminXYG.index'
import { Route as AtmIdRouteImport } from './routes/atm.$id'
import { Route as AdminXYGUsersRouteImport } from './routes/AdminXYG.users'
import { Route as AdminXYGSettingsRouteImport } from './routes/AdminXYG.settings'
import { Route as AdminXYGReportsRouteImport } from './routes/AdminXYG.reports'
import { Route as AdminXYGLogsRouteImport } from './routes/AdminXYG.logs'
import { Route as AdminXYGBanksRouteImport } from './routes/AdminXYG.banks'
import { Route as AdminXYGAtmsRouteImport } from './routes/AdminXYG.atms'
import { Route as AdminXYGAnalyticsRouteImport } from './routes/AdminXYG.analytics'
import { Route as AdminXYGAdminsRouteImport } from './routes/AdminXYG.admins'

const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NearbyRoute = NearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AddAtmRoute = AddAtmRouteImport.update({
  id: '/add-atm',
  path: '/add-atm',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminXYGRoute = AdminXYGRouteImport.update({
  id: '/AdminXYG',
  path: '/AdminXYG',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminXYGIndexRoute = AdminXYGIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AtmIdRoute = AtmIdRouteImport.update({
  id: '/atm/$id',
  path: '/atm/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminXYGUsersRoute = AdminXYGUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGSettingsRoute = AdminXYGSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGReportsRoute = AdminXYGReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGLogsRoute = AdminXYGLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGBanksRoute = AdminXYGBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGAtmsRoute = AdminXYGAtmsRouteImport.update({
  id: '/atms',
  path: '/atms',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGAnalyticsRoute = AdminXYGAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminXYGRoute,
} as any)
const AdminXYGAdminsRoute = AdminXYGAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AdminXYGRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/AdminXYG': typeof AdminXYGRouteWithChildren
  '/add-atm': typeof AddAtmRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/AdminXYG/admins': typeof AdminXYGAdminsRoute
  '/AdminXYG/analytics': typeof AdminXYGAnalyticsRoute
  '/AdminXYG/atms': typeof AdminXYGAtmsRoute
  '/AdminXYG/banks': typeof AdminXYGBanksRoute
  '/AdminXYG/logs': typeof AdminXYGLogsRoute
  '/AdminXYG/reports': typeof AdminXYGReportsRoute
  '/AdminXYG/settings': typeof AdminXYGSettingsRoute
  '/AdminXYG/users': typeof AdminXYGUsersRoute
  '/atm/$id': typeof AtmIdRoute
  '/AdminXYG/': typeof AdminXYGIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/add-atm': typeof AddAtmRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/AdminXYG/admins': typeof AdminXYGAdminsRoute
  '/AdminXYG/analytics': typeof AdminXYGAnalyticsRoute
  '/AdminXYG/atms': typeof AdminXYGAtmsRoute
  '/AdminXYG/banks': typeof AdminXYGBanksRoute
  '/AdminXYG/logs': typeof AdminXYGLogsRoute
  '/AdminXYG/reports': typeof AdminXYGReportsRoute
  '/AdminXYG/settings': typeof AdminXYGSettingsRoute
  '/AdminXYG/users': typeof AdminXYGUsersRoute
  '/atm/$id': typeof AtmIdRoute
  '/AdminXYG': typeof AdminXYGIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/AdminXYG': typeof AdminXYGRouteWithChildren
  '/add-atm': typeof AddAtmRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/nearby': typeof NearbyRoute
  '/notifications': typeof NotificationsRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/report': typeof ReportRoute
  '/AdminXYG/admins': typeof AdminXYGAdminsRoute
  '/AdminXYG/analytics': typeof AdminXYGAnalyticsRoute
  '/AdminXYG/atms': typeof AdminXYGAtmsRoute
  '/AdminXYG/banks': typeof AdminXYGBanksRoute
  '/AdminXYG/logs': typeof AdminXYGLogsRoute
  '/AdminXYG/reports': typeof AdminXYGReportsRoute
  '/AdminXYG/settings': typeof AdminXYGSettingsRoute
  '/AdminXYG/users': typeof AdminXYGUsersRoute
  '/atm/$id': typeof AtmIdRoute
  '/AdminXYG/': typeof AdminXYGIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/AdminXYG'
    | '/add-atm'
    | '/auth'
    | '/favorites'
    | '/nearby'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/report'
    | '/AdminXYG/admins'
    | '/AdminXYG/analytics'
    | '/AdminXYG/atms'
    | '/AdminXYG/banks'
    | '/AdminXYG/logs'
    | '/AdminXYG/reports'
    | '/AdminXYG/settings'
    | '/AdminXYG/users'
    | '/atm/$id'
    | '/AdminXYG/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/add-atm'
    | '/auth'
    | '/favorites'
    | '/nearby'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/report'
    | '/AdminXYG/admins'
    | '/AdminXYG/analytics'
    | '/AdminXYG/atms'
    | '/AdminXYG/banks'
    | '/AdminXYG/logs'
    | '/AdminXYG/reports'
    | '/AdminXYG/settings'
    | '/AdminXYG/users'
    | '/atm/$id'
    | '/AdminXYG'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/AdminXYG'
    | '/add-atm'
    | '/auth'
    | '/favorites'
    | '/nearby'
    | '/notifications'
    | '/onboarding'
    | '/profile'
    | '/report'
    | '/AdminXYG/admins'
    | '/AdminXYG/analytics'
    | '/AdminXYG/atms'
    | '/AdminXYG/banks'
    | '/AdminXYG/logs'
    | '/AdminXYG/reports'
    | '/AdminXYG/settings'
    | '/AdminXYG/users'
    | '/atm/$id'
    | '/AdminXYG/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AdminXYGRoute: typeof AdminXYGRouteWithChildren
  AddAtmRoute: typeof AddAtmRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  NearbyRoute: typeof NearbyRoute
  NotificationsRoute: typeof NotificationsRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  ReportRoute: typeof ReportRoute
  AtmIdRoute: typeof AtmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nearby': {
      id: '/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof NearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-atm': {
      id: '/add-atm'
      path: '/add-atm'
      fullPath: '/add-atm'
      preLoaderRoute: typeof AddAtmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminXYG': {
      id: '/AdminXYG'
      path: '/AdminXYG'
      fullPath: '/AdminXYG'
      preLoaderRoute: typeof AdminXYGRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminXYG/': {
      id: '/AdminXYG/'
      path: '/'
      fullPath: '/AdminXYG/'
      preLoaderRoute: typeof AdminXYGIndexRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/atm/$id': {
      id: '/atm/$id'
      path: '/atm/$id'
      fullPath: '/atm/$id'
      preLoaderRoute: typeof AtmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/AdminXYG/users': {
      id: '/AdminXYG/users'
      path: '/users'
      fullPath: '/AdminXYG/users'
      preLoaderRoute: typeof AdminXYGUsersRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/settings': {
      id: '/AdminXYG/settings'
      path: '/settings'
      fullPath: '/AdminXYG/settings'
      preLoaderRoute: typeof AdminXYGSettingsRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/reports': {
      id: '/AdminXYG/reports'
      path: '/reports'
      fullPath: '/AdminXYG/reports'
      preLoaderRoute: typeof AdminXYGReportsRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/logs': {
      id: '/AdminXYG/logs'
      path: '/logs'
      fullPath: '/AdminXYG/logs'
      preLoaderRoute: typeof AdminXYGLogsRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/banks': {
      id: '/AdminXYG/banks'
      path: '/banks'
      fullPath: '/AdminXYG/banks'
      preLoaderRoute: typeof AdminXYGBanksRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/atms': {
      id: '/AdminXYG/atms'
      path: '/atms'
      fullPath: '/AdminXYG/atms'
      preLoaderRoute: typeof AdminXYGAtmsRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/analytics': {
      id: '/AdminXYG/analytics'
      path: '/analytics'
      fullPath: '/AdminXYG/analytics'
      preLoaderRoute: typeof AdminXYGAnalyticsRouteImport
      parentRoute: typeof AdminXYGRoute
    }
    '/AdminXYG/admins': {
      id: '/AdminXYG/admins'
      path: '/admins'
      fullPath: '/AdminXYG/admins'
      preLoaderRoute: typeof AdminXYGAdminsRouteImport
      parentRoute: typeof AdminXYGRoute
    }
  }
}

interface AdminXYGRouteChildren {
  AdminXYGAdminsRoute: typeof AdminXYGAdminsRoute
  AdminXYGAnalyticsRoute: typeof AdminXYGAnalyticsRoute
  AdminXYGAtmsRoute: typeof AdminXYGAtmsRoute
  AdminXYGBanksRoute: typeof AdminXYGBanksRoute
  AdminXYGLogsRoute: typeof AdminXYGLogsRoute
  AdminXYGReportsRoute: typeof AdminXYGReportsRoute
  AdminXYGSettingsRoute: typeof AdminXYGSettingsRoute
  AdminXYGUsersRoute: typeof AdminXYGUsersRoute
  AdminXYGIndexRoute: typeof AdminXYGIndexRoute
}

const AdminXYGRouteChildren: AdminXYGRouteChildren = {
  AdminXYGAdminsRoute: AdminXYGAdminsRoute,
  AdminXYGAnalyticsRoute: AdminXYGAnalyticsRoute,
  AdminXYGAtmsRoute: AdminXYGAtmsRoute,
  AdminXYGBanksRoute: AdminXYGBanksRoute,
  AdminXYGLogsRoute: AdminXYGLogsRoute,
  AdminXYGReportsRoute: AdminXYGReportsRoute,
  AdminXYGSettingsRoute: AdminXYGSettingsRoute,
  AdminXYGUsersRoute: AdminXYGUsersRoute,
  AdminXYGIndexRoute: AdminXYGIndexRoute,
}

const AdminXYGRouteWithChildren = AdminXYGRoute._addFileChildren(
  AdminXYGRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AdminXYGRoute: AdminXYGRouteWithChildren,
  AddAtmRoute: AddAtmRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  NearbyRoute: NearbyRoute,
  NotificationsRoute: NotificationsRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  ReportRoute: ReportRoute,
  AtmIdRoute: AtmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
